### ISSUE TITLE
Problem with teamspeak 700 slots

### ISSUE THREAD

**Issue by samuxita** [v10networkscom/saltychat-docs#40]
My teamspeak server have 23% of packetloss when the server reach about 600 users. The CPU usage is optimal, spec are ryzen9 3950x and 2Gbit uplink. I don’t know why this teamspeak have this packetloss “Out”. “i’m using saltychat for fivem server on this teamspeak”.

![image](https://user-images.githubusercontent.com/35420397/132650343-48d06e31-71f3-4f77-8995-382d22916ad7.png)
![image](https://user-images.githubusercontent.com/35420397/132650393-223ccfca-2cba-43e2-b058-263f235d5b49.png)

The packet loss out is only visible on “control” table.
![image](https://user-images.githubusercontent.com/35420397/132650437-67c532cc-aff1-4953-b055-8222d4a526b9.png)

Teamspeak said that is a problem of salty chat

**Comment by BlackFlash5** [comment]
Issue described in #41, 3.0.0p1 is now available and issues can be reported in the issue or Discord.
