### ISSUE TITLE
[Feature-Request] Provide command for "always whisper" list

### ISSUE THREAD

**Issue by deluvas1911** [v10networkscom/saltychat-docs#47]
### Is your proposal related to a problem?
Related to current change from (un)mute to whisper

### Describe the feature you'd like
Provide a command which sets up players as "always-whisper" targets.
I don't know about the functionality of FiveM, but alt:V uses a dimension system so players in dimension 1 don't receive data about players in dimension 2, but there are negative dimensions where players can see others but can't be seen.
Related to support cases those negative dimensions are often used, but as the other players don't receive any data about the support character they don't add him to the whisper list.
This could be also useful for supporters outside the ingame channel to listen to specific players.

### Sample case
1. Server sends command like "AlwaysWhisper" with teamspeak client xyz & true
2. Regarding of the data from the batch update, the clients from the always whisper get also added to the whisper list
3. Support can do his job again

#### Log of current behaviour
Not applicable

**Comment by BlackFlash5** [comment]
Why don't you create a player state with the same pos as the local client to do that?
The client has to know who the "permanent" whisper target is anyways and could just send a player state instead of having separate commands to handle that.

**Comment by deluvas1911** [comment]
Nevermind this issue. At first your option is right, at the 2nd I would need to update the invisible clients position anyway from the server, so I need to find some (performant) workaround for this :D

**Comment by BlackFlash5** [comment]
> I would need to update the invisible clients position anyway from the server
As i said before, you don't if you just send the position of the local player.
