### ISSUE TITLE
Phone Error

### ISSUE THREAD

**Issue by shaunluedeke** [v10networkscom/saltychat-docs#50]
Hi everyone. We downloaded the latest version of SaltyChat (3.0.5) from git for AltV. But we have the problem that when you call and hang up again the user can still be heard. You can fix the problem if you call again and the person calling hangs up. Can one of you help me. Kind regards

**Comment by WhiteRhino09FB** [comment]
I can confirm that we are having the exact same issue on fivem

**Comment by CrazyKee** [comment]
Same here

**Comment by shaunluedeke** [comment]
the error is in the Voice Manager.cs class the list _phoneCalls has no check of who the caller is
