### ISSUE TITLE
Salty Chat Trojan

### ISSUE THREAD

**Issue by SenorLordy** [v10networkscom/saltychat-docs#59]
Version: 3.1.0
![sctrojaner_2](https://github.com/v10networkscom/saltychat-docs/assets/94993276/14dc5463-9ed6-464f-b8db-57b381a769d1)

**Comment by BlackFlash5** [comment]
I've never heard of `MaxSecure` and I couldn't even find a way to report false positives (like proper antivirus solutions).
1 out of 65 is also a pretty clear indicator of a false positive (at least in a case of an no name antivirus).
